name: Deployment

on:
  release:
    types:
      - created

jobs:
  dist_linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Update Libs
      run: apk add --update --upgrade --no-cache --force-overwrite libxml2-dev yaml yaml-dev openssl-dev
    - name: Build
      run: |
        shards build --production --release --static --no-debug
    - name: Upload
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ./bin/kittn-server
          ./bin/kittn-pack
